services:
  postgres:
    image: 'postgres:latest'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydatabase']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    networks:
      - gde-network
    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: 'dpage/pgadmin4:latest'
    restart: unless-stopped
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=admin@example.com'
      - 'PGADMIN_DEFAULT_PASSWORD=admin'
    ports:
      - '5050:80'
    networks:
      - gde-network
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend/gde_website
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase'
      - 'SPRING_DATASOURCE_USERNAME=myuser'
      - 'SPRING_DATASOURCE_PASSWORD=secret'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - gde-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - gde-network  


networks:
  gde-network:
    driver: bridge

volumes:
  postgres_data:
