# Checks links inside Markdown and HTML repo files

# What type of files need to be checked
include = ["**/*.md", "**/*.html"]

# Excluded links
exclude = [
    "https://localhost",
    "http://localhost",
]

# Тimeout in seconds
timeout = 10

# Maximum number of parralel requests
max_parallel = 10